services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    restart: unless-stopped
    ports:
      - ${ZT_IP:-127.0.0.1}:20201:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/ServerData/dockhand/data:/app/data
      - ~/OtoCLI/Management:/mnt/Management-compose
    networks:
      - proxy_network
      
networks:
  proxy:
    external: true
